services:
  - type: web
    name: reglog-backend
    runtime: java
    plan: free
    rootDir: .
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/reglog-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
